version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
      - echo "NPM install completed"
      - npm ls --depth=0

  build:
    commands:
      - dnf install -y xorg-x11-server-Xvfb gtk3-devel nss alsa-lib
      - npm run cy:parallel
