version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm --version
      - node --version
      - npm install

  build:
    commands:
      - npm run cy:parallel
