version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - dnf install -y xorg-x11-server-Xvfb gtk3-devel nss alsa-lib
      - npm install
      - echo "NPM install completed"
      - npm ls --depth=0

  build:
    commands:
      - npm run test-ci
  post_build:
    commands:
      - aws s3 sync allure-report s3://dashboard-pruebas-cypress/
      - aws s3 cp --recursive --acl public-read s3://dashboard-pruebas-cypress/ s3://dashboard-pruebas-cypress/ --metadata-directive REPLACE
      - echo "The HTML report can be found here <http://dashboard-pruebas-cypress.s3-website.us-east-2.amazonaws.com>"
