version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install

  pre_build:
    commands:
      - echo "Pre-build phase complete"

  build:
    commands:
      - npm run cy:parallel
